### ISSUE TITLE
"Invalid URL"

### ISSUE THREAD

**Issue by koknese** [notangelmario/gread#1]
Opening https://gread.deno.dev/lazyvim.org/configuration/lazy.nvim or any other site doesn't work and gives me invalid URL error.

**Comment by m4rocks** [comment]
hello @gatesbydude! gread works by providing the full url including the protocol (for example https://). Correct usage would be https://gread.deno.dev/https://lazyvim.org/configuration/lazy.nvim

I will look into auto-correcting urls.
